from pathlib import Path
import json, re, math, html
ROOT=Path(__file__).resolve().parent
BASE='https://frhino067.github.io/cao-finder/'
DATE='2026-09-19'
A=[]
def add(slug,cat,title,desc,dek,take,sections,faq,related):
 A.append(dict(slug=slug,cat=cat,title=title,desc=desc,dek=dek,take=take,sections=sections,faq=faq,related=related))
add('how-to-choose-a-cao-course','Choosing a course','How to choose a CAO course when you have no idea what to study','Unsure what to put on your CAO? Use a practical shortlist method to compare modules, entry requirements, location and the work you actually enjoy.',
'You do not need a perfect career plan to choose a useful next step. Start with the work you enjoy doing, then test a small shortlist against real course details.',
'Choose a course you can explain in terms of its modules and daily work, not just its title or the points attached to it.',[
('Start with tasks, not job titles','''<p>“I want a good career” does not narrow down a course search very much. “I like arguing a case, interpreting graphs and explaining an idea” gives you something to work with. Write down three school tasks you would choose and three you consistently avoid. Include projects, practical work, presentations and independent reading.</p><p>Separate interest from marks. You may enjoy a subject you currently find difficult, or get good results in one you do not want to study for several years. Both observations matter. Ask what you would willingly spend more time learning if there were no test tomorrow.</p>'''),
('Build a shortlist in three passes','''<ol><li><strong>Explore:</strong> pick three subject areas and save a few courses from each. Keep this first list deliberately broad.</li><li><strong>Inspect:</strong> open the official course pages and read the compulsory first-year modules. Highlight what attracts you and what worries you.</li><li><strong>Test:</strong> compare teaching, assessment, location and practical constraints. Reduce the list only when you can give a reason.</li></ol><p>Set a 30-minute limit for the first search. You are making a starting list, not a final life decision. A shorter research session with notes is more useful than dozens of open tabs you cannot remember.</p>'''),
('Use a comparison you can actually defend','''<div class="table-wrap"><table><thead><tr><th>Question</th><th>Evidence to collect</th></tr></thead><tbody><tr><td>Will I like the work?</td><td>Three compulsory modules and a sample assignment</td></tr><tr><td>How will I be assessed?</td><td>Exams, projects, labs, essays or presentations</td></tr><tr><td>Can I manage the week?</td><td>Campus, travel route and likely on-site commitments</td></tr><tr><td>What can come next?</td><td>Placement details and named progression options</td></tr></tbody></table></div><p>For example, two courses called Business might offer very different combinations of accounting, languages and placement. Do not give them the same score simply because the names match.</p>'''),
('Check the deal-breakers before ranking','''<p>Confirm subject and grade requirements on each college’s current page. Entry requirements are separate from a points total; the <a href="https://www2.cao.ie/handbook/handbook2027/hb.pdf">CAO handbook</a> explains why eligibility must be checked first.</p><p>Then decide your own non-negotiables: a manageable commute, a particular subject, or a placement you can realistically attend. Treat “I do not know yet” as a research task rather than silently giving a course a pass.</p>'''),
('Finish with one useful conversation','''<p>Bring three course pages and your notes to a guidance counsellor, teacher or open day. Ask a specific question: “I like the policy modules but struggle with maths; what quantitative work is compulsory?” A precise question gives someone a chance to help.</p><p>Your next action is simple: choose three courses, write one reason for each, and identify one unanswered question. You can refine the shortlist as your knowledge improves.</p>''')],
('What if none of the courses feels perfect?','Look for a course with several things you want to learn and constraints you can manage. Explore further education and other routes with your guidance counsellor too; uncertainty is a reason to investigate, not to pick at random.'),[2,6,8])
add('leaving-cert-cao-points-explained','CAO & points','Leaving Cert points explained: calculate your best six correctly','Calculate Leaving Cert CAO points with a grade table, a seven-subject worked example and an explanation of the Higher Maths bonus.',
'A points total is useful only if you calculate it correctly. Here is a worked example you can copy, including the subject that drops out of the best six.',
'Convert grades to points, add any eligible Higher Maths bonus to maths, then take the six highest scores from one sitting.',[
('The Higher and Ordinary Level points table','''<p>The standard grade values below come from the <a href="https://www.cao.ie/index.php?page=scoring&amp;s=lcepointsgrid">official CAO scoring grid</a>. The six best recognised subject results from one sitting count. You must also meet course entry requirements.</p><div class="table-wrap"><table><thead><tr><th>Grade number</th><th>Higher Level</th><th>Ordinary Level</th></tr></thead><tbody><tr><td>1</td><td>H1: 100</td><td>O1: 56</td></tr><tr><td>2</td><td>H2: 88</td><td>O2: 46</td></tr><tr><td>3</td><td>H3: 77</td><td>O3: 37</td></tr><tr><td>4</td><td>H4: 66</td><td>O4: 28</td></tr><tr><td>5</td><td>H5: 56</td><td>O5: 20</td></tr><tr><td>6</td><td>H6: 46</td><td>O6: 12</td></tr><tr><td>7</td><td>H7: 37</td><td>O7: 0</td></tr><tr><td>8</td><td>H8: 0</td><td>O8: 0</td></tr></tbody></table></div>'''),
('A seven-subject example: 467 points','''<p>This is an invented example, not a predicted set of results. Suppose a student gets English H2, Irish O2, Maths H4, Economics H3, Geography H3, Biology H4 and French H4.</p><div class="table-wrap"><table><thead><tr><th>Subject</th><th>Score</th><th>Counted?</th></tr></thead><tbody><tr><td>Maths H4</td><td>66 + 25 = 91</td><td>Yes</td></tr><tr><td>English H2</td><td>88</td><td>Yes</td></tr><tr><td>Economics H3</td><td>77</td><td>Yes</td></tr><tr><td>Geography H3</td><td>77</td><td>Yes</td></tr><tr><td>Biology H4</td><td>66</td><td>Yes</td></tr><tr><td>French H4</td><td>66</td><td>Yes</td></tr><tr><td>Irish O2</td><td>46</td><td>No</td></tr></tbody></table></div><p><strong>91 + 88 + 77 + 77 + 66 + 66 = 467.</strong> Irish is still relevant to any applicable entry requirement even though it does not contribute to this total.</p>'''),
('Why the maths bonus goes in before sorting','''<p>An eligible H6 or better in Higher Maths receives 25 extra points. Maths contributes to the total only if its adjusted score is among the best six. See <a href="https://www2.cao.ie/app_scoring/BonusPointsMathsWithExamples.pdf">CAO’s maths bonus examples</a>.</p><p>Use a column for each subject’s score rather than adding 25 to the final total automatically. That makes it much easier to see whether maths actually displaced another subject.</p>'''),
('Turn a total into a planning tool','''<p>Make three versions of your estimate: grades you have already demonstrated consistently, a reasonable improvement, and a stretch scenario. Label them clearly. A good mock or difficult class test should not become a guarantee about the final exam.</p><p>Change one grade at a time and recalculate. In the example above, moving Economics from H3 to H2 would add 11 points. Improving Irish from O2 to O1 would not change the best-six total in that example, although the result could still matter for other reasons.</p>'''),
('Know what the calculator does not cover','''<p>CAO Finder’s calculator handles Higher and Ordinary Level grades and the maths bonus. It does not model LCVP, Foundation Level or medicine’s adjusted scoring. Use official guidance for those cases.</p><p>After calculating, check individual course requirements and the year shown beside historical points. A total helps you explore; it is not an offer or an eligibility decision.</p>''')],
('Does a seventh subject add extra points?','Only the best six count towards the standard total. A seventh subject can enter that six if its score is high enough, and can also matter for entry requirements.'),[2,5,6])
add('cao-order-of-preference','CAO & points','CAO order of preference: how to rank your courses properly','Learn how to order your CAO choices, keep Level 8 and Level 7/6 lists separate and avoid ranking courses by last year’s points.',
'Your CAO list should express what you want to study. It is not a prediction of what points you will get, and it is not a league table of colleges.',
'Put the course you genuinely want most first. Use historical points to explore options, not to decide the order of your preferences.',[
('Keep preference and prediction separate','''<p>CAO advises applicants to rank courses in <a href="https://www2.cao.ie/downloads/documents/course_choices_list.pdf">genuine order of preference</a>. Its Level 8 and Level 7/6 lists are independent. Each list has space for up to ten choices.</p><p>Write two different questions at the top of your research page: “Would I want this course?” and “What do I need to qualify?” They both deserve attention, but they are not interchangeable. Feeling unsure about your predicted points does not tell you whether you prefer one course over another.</p>'''),
('An example of a preference list','''<p>Imagine you prefer Course A to Course B, and Course B to Course C. Their previous points were 510, 460 and 480 respectively. Your order should still be A, B, C. The figures do not move C above B.</p><p>These are fictional courses and points. The example is useful because it strips away prestige, parental expectations and the temptation to arrange everything numerically. If the points were hidden, which offer would you be happiest to open?</p>'''),
('Use a pair-by-pair check','''<ol><li>Compare choices one and two. If both were available, which would you take?</li><li>Repeat for two and three, then continue down the list.</li><li>For any difficult pair, compare compulsory modules and the practical college week.</li><li>Move a course only when your preference changes, then recheck its neighbours.</li></ol><p>A tie often means you are missing information. Find the missing detail: perhaps one course has a compulsory language, a different campus, or a placement arrangement you have not checked. Resolve that question before trying to force a ranking.</p>'''),
('Understand what a later offer can change','''<p>CAO’s <a href="https://www2.cao.ie/downloads/documents/course_choices_list.pdf">offer examples</a> explain that an offer removes lower preferences on that same list from further consideration. Higher preferences can remain in play; accepting an earlier offer does not itself prevent a later higher-preference offer. Always read the reply deadline and instructions on your actual offer.</p><p>This is why a course you would never accept should not sit above one you really want. It is also why you should judge an actual offer carefully rather than assume another will arrive.</p>'''),
('A final check before you save changes','''<ul><li>Read every course code beside its title and campus.</li><li>Check the qualification level and all compulsory requirements.</li><li>Make sure every choice represents an option you would consider taking.</li><li>Recheck both lists, not just the Level 8 list.</li><li>Confirm the changes were saved in your official CAO account.</li></ul><p>CAO Finder’s saved list is a research tool. It does not submit an application or set your official preference order. Keep a dated personal copy of your intended order so you can compare it with the account later.</p>''')],
('Should I put a lower-points course first to be safe?','Put it first if it is your favourite. A previous points figure should not be the reason you place it above a course you prefer.'),[0,1,6])
add('leaving-cert-study-timetable','Study & school','A Leaving Cert study timetable you can actually stick to','Build a flexible Leaving Cert study timetable around school, homework and activities, with a sample week and a simple review method.',
'The best timetable is one you can use on an ordinary Wednesday. Build around the week you really have, then give each study block a clear job.',
'Plan specific tasks in realistic spaces. Leave room for homework, breaks and the sessions that inevitably need to move.',[
('Start with the fixed parts of your week','''<p>Put school, travel, meals, activities, family commitments and your usual bedtime into a weekly grid before adding revision. Homework already takes time: count it instead of pretending every evening begins with a blank page.</p><p>Now identify a few usable gaps. A short session after a busy day might be enough for one marked question. A quieter weekend morning might suit a longer piece of writing. Do not copy a classmate’s hours if their week is nothing like yours.</p>'''),
('Replace subject labels with finish lines','''<p>“Maths, 7–8” is vague. “Attempt three differentiation questions, mark them and redo one error” tells you what completion looks like. Use the same approach across subjects: plan a comparative paragraph, practise one oral topic, or explain a diagram from memory before checking it.</p><p>Keep a small next-task list for each subject. If a teacher gives urgent homework, you can swap a block without spending twenty minutes deciding what to do. A timetable should reduce decisions, not create another assignment.</p>'''),
('A sample week to adapt','''<div class="table-wrap"><table><thead><tr><th>Day</th><th>Example revision task after homework</th></tr></thead><tbody><tr><td>Monday</td><td>Maths: three questions and an error review</td></tr><tr><td>Tuesday</td><td>English: plan and write one timed paragraph</td></tr><tr><td>Wednesday</td><td>Irish: practise one oral topic; check missing phrases</td></tr><tr><td>Thursday</td><td>Economics: explain a concept and answer one application question</td></tr><tr><td>Friday</td><td>Short catch-up or a planned evening off</td></tr><tr><td>Saturday</td><td>Geography and another subject: one focused task each</td></tr><tr><td>Sunday</td><td>Review the week and choose next week’s tasks</td></tr></tbody></table></div><p>This is a structure, not a recommended number of hours. Swap subjects and session lengths to fit your own workload. Add breaks between demanding tasks rather than stretching one session until you stop concentrating.</p>'''),
('Make room for weak topics without abandoning everything else','''<p>Choose one topic that is currently blocking progress and give it a clear next step. For maths, that might be revisiting an algebra skill before trying a harder question. For an essay subject, it might be getting feedback on how you develop a point.</p><p>Keep smaller maintenance tasks for stronger subjects. A whole week spent fixing one weakness can leave you behind elsewhere. If your list is impossible to fit, ask a teacher which tasks matter most before adding more hours.</p>'''),
('Use a ten-minute weekly reset','''<p>Ask: what did I actually finish, what mistake keeps recurring, and what should I change next week? Move unfinished tasks deliberately. Do not simply copy an overloaded plan forward.</p><p>Protect time away from schoolwork. If the plan repeatedly runs into bedtime or leaves no recovery time, reduce the load and seek help prioritising. A sustainable timetable should serve you through the year, not look impressive for two days.</p>''')],
('How many hours should I study each night?','There is no single number that fits every student. Start with the tasks you need, account for homework and commitments, and adjust using what you actually manage to finish.'),[4,5,0])
add('how-to-use-leaving-cert-past-papers','Study & school','How to use Leaving Cert past papers without wasting them','Use Leaving Cert past papers to find gaps, practise timing and learn from marking schemes with a repeatable attempt-mark-redo routine.',
'Doing a paper is only the first half of the job. The useful part is working out why you lost marks and whether you can fix the same mistake next time.',
'Attempt, mark, diagnose and redo. Keep a short error log so each paper changes what you study next.',[
('Choose a question with a purpose','''<p>Before opening a paper, decide what you are testing: understanding a topic, recalling material without notes, interpreting a question or working within time. Those are different jobs. Early in a topic, an untimed question can be more useful than a whole paper you cannot finish.</p><p>Use the <a href="https://www.examinations.ie/exammaterialarchive/">State Examinations Commission’s exam material archive</a> for official papers and marking schemes. Check the year, subject and level. Ask your teacher which older papers still match the syllabus and assessment arrangements for your exam year.</p>'''),
('Try before opening the marking scheme','''<p>Write an actual answer, including the steps you are unsure about. If you get stuck, note the point where you stopped. Reading a solution and thinking “I would have done that” gives you much less information than seeing what you produce on your own.</p><p>Keep hints separate. If you needed a formula reminder or a paragraph outline, label that attempt as supported. You can still learn from it, but it should not be mistaken for independent exam performance.</p>'''),
('Classify the mistake, then choose the repair','''<div class="table-wrap"><table><thead><tr><th>What happened?</th><th>What to do next</th></tr></thead><tbody><tr><td>I did not know the concept</td><td>Revisit the lesson and attempt a simpler question</td></tr><tr><td>I knew it but misread the task</td><td>Underline the command and rephrase what it asks</td></tr><tr><td>My answer lacked development</td><td>Add a specific explanation or supporting example</td></tr><tr><td>I made a calculation error</td><td>Locate the first wrong step, then redo the working</td></tr><tr><td>I ran out of time</td><td>Practise a shorter timed section and review pacing</td></tr></tbody></table></div><p>Do not record only “lost 12 marks”. That does not tell you what tomorrow’s session should contain.</p>'''),
('Keep an error log that takes one minute','''<p>Use four columns: question, mistake, repair and retest date. A useful entry might read: “Differentiation question; forgot the chain rule; do two short chain-rule questions; retry on Thursday.”</p><p>When you return, start from a blank page. If you reproduce the method independently, move on to a different question that uses the same skill. If you cannot, bring the exact sticking point to your teacher. For extended writing, ask for feedback when you cannot confidently interpret the marking criteria yourself.</p>'''),
('Use full papers to practise the whole performance','''<p>Once you can handle individual sections, practise choosing questions, allocating time and checking work across a full paper. Follow the instructions for that paper; do not assume an old choice structure applies to your current examination.</p><p>Never treat repeated topics as a guarantee of what will appear. Past papers are evidence about your preparation, not a promise about the next exam. End each practice session with one concrete improvement task.</p>''')],
('Should I memorise marking-scheme answers?','Use a scheme to understand what earns credit, then practise applying the knowledge to a differently worded question. Copying a model answer is not the same as being able to answer independently.'),[3,5,1])
add('higher-or-ordinary-level-maths','Study & school','Higher or Ordinary Level Maths? A practical decision checklist','Compare Higher and Ordinary Level Maths using course requirements, realistic grades, the bonus points rule and the effect on your other subjects.',
'This decision deserves more than “Higher has bonus points”. Look at the courses you want, the work required and the grades you can realistically demonstrate.',
'Check course eligibility first, compare realistic best-six totals second, and discuss the learning workload with your maths teacher.',[
('Check whether your target courses need Higher Maths','''<p>Make a small table of the courses you are seriously considering and copy their exact maths requirements from the current college pages. Record the course code and application year. If a requirement is unclear, ask the college admissions office rather than guessing.</p><p>A large overall points score does not replace a missing required subject grade. Equally, do not assume every course in a broad area has identical requirements. Start with evidence for your actual shortlist.</p>'''),
('Understand what the bonus does—and does not do','''<p>The <a href="https://www2.cao.ie/app_scoring/BonusPointsMathsWithExamples.pdf">CAO maths bonus rules</a> award 25 additional points for H6 or better in Higher Maths. The adjusted maths score must be in your best six to contribute. The bonus is not a separate pass in maths and does not change the grade printed on your result.</p><p>As a simple comparison, H6 gives 71 including the bonus, while O1 gives 56 on the <a href="https://www.cao.ie/index.php?page=scoring&amp;s=lcepointsgrid">standard grid</a>. But those are two different possible performances, not proof that one level is right for you.</p>'''),
('Compare complete scenarios, not isolated scores','''<p>Write down a realistic grade for every subject under each option, then calculate both best-six totals. Label the estimates as uncertain. Consider whether extra maths work would replace time you need for other subjects, or whether the challenge is manageable with a better plan.</p><p>Do not compare your most optimistic Higher result with your most pessimistic Ordinary result. Use teacher feedback, independent attempts and recent work. If the outcome changes dramatically when one assumed grade changes, that uncertainty should be part of the discussion.</p>'''),
('Bring useful evidence to your teacher','''<ul><li>Two recent independent pieces of work, including your working.</li><li>The topics where you lose the most marks.</li><li>The maths requirements of three courses you like.</li><li>A realistic account of your weekly homework and revision time.</li><li>Your questions about what catching up would involve.</li></ul><p>Ask, “Which gaps would I need to close to reach this grade, and how will we check progress?” That is more actionable than asking for a prediction without showing your work.</p>'''),
('Set a review point rather than drifting','''<p>If you decide to continue at Higher Level for now, agree on specific topics to work on and a date to review progress. If you change level, ask what material and exam technique you need to learn for the new course. Neither option should mean stopping maths practice.</p><p>Check school and examination procedures before changing level. Keep your course shortlist current, because a decision that suits your workload can affect which entry requirements you meet. Make the choice with your teacher and guidance counsellor, not with a points comparison alone.</p>''')],
('Is staying at Higher Level always worth it for the bonus?','No. The answer depends on the grade you can achieve, whether maths enters your best six, the requirements of your chosen courses and the effect on the rest of your work.'),[1,3,6])
add('cao-entry-requirements-subjects','CAO & points','CAO entry requirements: why enough points may not be enough','Check CAO subject and grade requirements separately from points with a simple course eligibility checklist for Leaving Cert students.',
'A points figure answers only one part of the admissions question. Before saving a course as a serious option, check that your subjects and qualifications meet its requirements.',
'Treat eligibility as a checklist of exact conditions, then consider points. A points filter cannot confirm that a college will accept your application.',[
('Separate the three checks','''<p>For each course, look for general college entry requirements, course-specific requirements and any extra assessment or application conditions. The <a href="https://www2.cao.ie/handbook/handbook2027/hb.pdf">CAO handbook</a> tells applicants to verify minimum entry requirements with institutions and explains that restricted courses may involve additional assessments.</p><p>Read these as separate boxes. Meeting one does not automatically meet the others. A course page may link to a general admissions page, so follow that link instead of stopping at the short summary beside the course title.</p>'''),
('Copy exact wording into an eligibility sheet','''<div class="table-wrap"><table><thead><tr><th>Check</th><th>What to record</th></tr></thead><tbody><tr><td>Identity</td><td>Course code, campus, level and entry year</td></tr><tr><td>General requirements</td><td>Number of subjects, levels and minimum grades</td></tr><tr><td>Named subjects</td><td>Required subject and exact grade</td></tr><tr><td>Extra steps</td><td>Assessment, portfolio or other listed condition</td></tr><tr><td>Uncertainty</td><td>Your question, source link and date checked</td></tr></tbody></table></div><p>Use “confirmed”, “not met” and “need to ask” rather than a single yes/no field. An unresolved condition should stay visible until you have an answer.</p>'''),
('Read “and” and “or” carefully','''<p>Consider a fictional requirement: “H4 in Mathematics and H5 in one laboratory science.” That asks for both conditions. “H4 in Mathematics or H4 in Applied Mathematics” describes alternatives. These examples are illustrations only and are not the requirements of any named course.</p><p>Make sure a note about an exemption, alternative qualification or special route actually applies to you. A friend’s circumstances or an older prospectus might be different. Save the current official page and ask for clarification when two pages appear inconsistent.</p>'''),
('Send a question the admissions office can answer','''<p>Use a short message: “I am considering [course code] for [entry year]. I take [relevant subjects and levels]. The entry page says [brief requirement]. Does [specific issue] meet this condition?” Avoid sending more personal information than the question needs.</p><p>If the reply points you to a document, read the relevant section and update your sheet. Keep the answer alongside the course code so you do not accidentally apply it to another programme at the same college.</p>'''),
('Use the finder as the start of the check','''<p>CAO Finder can narrow courses by points, college and category. Its subject and duration filters cover a limited verified subset, and unknown details remain unknown. A course missing from a filtered result is not proof that you are ineligible.</p><p>Open the college page for every serious choice, check the current year, and repeat the eligibility review before finalising your application. Use the <a href="https://www.cao.ie/index.php?page=studentresources">CAO applicant resources</a> to check any restrictions or supporting-document instructions relevant to your situation.</p>''')],
('Can bonus maths points make up for a required maths grade?','The bonus changes a points score, not your grade. Check the exact required grade and any accepted alternatives with the college.'),[1,2,5])
add('level-6-7-8-college-courses','College life & routes','Level 6, 7 and 8 courses in Ireland: what is the difference?','Compare Level 6 Higher Certificates, Level 7 degrees and Level 8 honours degrees, and learn what to ask before relying on a progression route.',
'The qualification level tells you something useful about the award. It does not, on its own, tell you which course will suit you or whether progression is guaranteed.',
'Compare the award, the actual course and the written progression conditions. Do not assume that a similar title means an automatic route into the next year.',[
('The basic qualification map','''<p>For the higher education awards commonly found in CAO searches, the <a href="https://www.qqi.ie/national-framework-of-qualifications">QQI framework</a> identifies the following:</p><div class="table-wrap"><table><thead><tr><th>NFQ level</th><th>Award</th><th>Usual full-time duration</th></tr></thead><tbody><tr><td>6</td><td>Higher Certificate</td><td>Two years</td></tr><tr><td>7</td><td>Ordinary Bachelor Degree</td><td>Three years</td></tr><tr><td>8</td><td>Honours Bachelor Degree</td><td>Three or four years; some are longer</td></tr></tbody></table></div><p>Level 6 also includes further education Advanced Certificates. Those are different awards from Higher Certificates. Check the full award name, not just the number.</p>'''),
('Compare what you would actually learn','''<p>Start with compulsory modules, practical work and assessment. If two programmes share a subject area, compare how far each takes that subject and what projects you would complete. Do not assume a shorter programme is simply the first part of another one.</p><p>Next, check whether the award meets any requirements attached to the career or later course you have in mind. Ask the relevant institution or professional body when recognition matters. A broad statement about a qualification level is not a substitute for that check.</p>'''),
('Ask these questions about progression','''<ul><li>What exact course and year can graduates apply to enter?</li><li>Is there a named arrangement, or only a possibility of applying?</li><li>What grades and modules are required?</li><li>Are places limited or competitive?</li><li>Would the next stage require a move to another campus?</li><li>How many years would the full route take?</li></ul><p>Write the answers beside each route. QQI describes add-on awards within the framework, but that does not establish the conditions for your particular college and course.</p>'''),
('Compare a direct route with a staged route','''<p>Imagine a student weighing a direct honours degree against a Higher Certificate followed by further study. The staged option might offer a useful earlier award or a convenient initial location. It might also depend on grades, available places and a later move.</p><p>Build two timelines showing study years, application points and any uncertain transition. This is an invented decision exercise, not a claim that a particular route exists. Ask the college to confirm the real version before relying on it.</p>'''),
('Keep both CAO lists useful','''<p>The Level 8 list and Level 7/6 list are independent, as the <a href="https://www2.cao.ie/downloads/documents/course_choices_list.pdf">CAO preference guide</a> explains. Research meaningful options for each rather than filling a list with courses you would not attend.</p><p>When searching CAO Finder, change the qualification filter to explore beyond the default Level 8 selection. Some entries remain labelled Level 6/7 where their precise level has not been confirmed in the dataset. Use the college’s current course page to resolve that detail.</p>''')],
('Is a Level 7 course automatically a route to Level 8?','No. A progression or add-on route must be checked for that specific programme, including the grades, modules, application process and available places.'),[0,6,8])
add('college-open-day-questions','Choosing a course','College open day questions: a checklist that goes beyond the brochure','Make college open days useful with specific questions about modules, assessment, placements, commuting and student support, plus a comparison template.',
'An open day is a chance to test whether a course fits your real week. Arrive with a shortlist and leave with answers you can compare.',
'Ask for examples of the actual student experience: a compulsory module, a typical week, an assignment and the practical details of any placement.',[
('Choose three questions before you travel','''<p>Read the official course page first and identify what it does not answer. If the modules are already listed, use your time to ask how they are taught or assessed. If a placement is advertised, ask how it is organised.</p><p>Pick your three most important questions and save them on your phone. Check the event schedule, campus and registration instructions directly with the college before travelling. Give yourself time to move between buildings instead of booking sessions back to back.</p>'''),
('Questions to ask teaching staff','''<ul><li>Which first-year module do new students find most surprising, and why?</li><li>Can you describe a typical assignment?</li><li>Which modules are compulsory, and when do students choose options?</li><li>How much work involves maths, writing, practical tasks or group projects?</li><li>What happens if an optional module has more applicants than places?</li><li>Who should I contact to confirm a particular entry requirement?</li></ul><p>These questions turn a general pitch into something you can imagine doing. Listen for concrete examples and note any answer that needs a follow-up link.</p>'''),
('Questions to ask current students','''<p>Ask what their week looks like, what they wish they had known and how they manage travel between classes. “How did you find your first group project?” is often easier to answer than “Is the course good?”</p><p>One student’s account is a perspective, not a guarantee. Compare it with official information and, where possible, another student’s experience. Avoid treating a very positive or very negative story as the whole picture.</p>'''),
('Check the practical details','''<div class="table-wrap"><table><thead><tr><th>Area</th><th>Question worth asking</th></tr></thead><tbody><tr><td>Placement</td><td>Is it compulsory, who finds it, and where might it be?</td></tr><tr><td>Campus</td><td>Are all years taught here?</td></tr><tr><td>Timetable</td><td>Can I see an illustrative week, including labs?</td></tr><tr><td>Support</td><td>How do students access learning and accessibility support?</td></tr><tr><td>Costs</td><td>Are there course-specific equipment or travel costs?</td></tr></tbody></table></div><p>An illustrative timetable can change. Use it to uncover questions about your commute or commitments, not to assume next year will be identical.</p>'''),
('Do a ten-minute debrief before the details blur','''<p>Write three things you liked, two concerns and one action. For example: “Liked the project work; worried about the placement location; email the coordinator for details.” Keep course-specific notes separate from your impression of the campus.</p><p>Then compare the visit with your other shortlisted courses. A lively atmosphere is a bonus, but the modules and practical commitments will shape far more of your week. If you cannot attend, use a virtual event or ask admissions for the same information.</p><p>Finally, change your shortlist only where the evidence changed your view. You do not need to make a decision on the train home.</p>''')],
('What should I bring to an open day?','Your course codes, three priority questions, a way to take notes and a travel plan. Check the college’s event instructions for anything else you need.'),[0,9,7])
add('commuting-to-college-or-moving-out','College life & routes','Commuting to college or moving out: how to compare your options','Compare commuting and moving for college using a weekly time test, a realistic cost worksheet and questions about campus and placement schedules.',
'The right college choice needs to fit the days between lectures too. Compare the full week, not just a map distance or a single rent figure.',
'Write down time, practical constraints and the costs you have actually checked. A short-looking journey can be very different at the times you need to travel.',[
('Test the journey door to door','''<p>Choose a plausible morning arrival time and a later finish. Look up the current route, transfers and the walk from the stop to the actual teaching building. If practical, try the journey at the relevant time. Add a note about what happens when a connection is missed.</p><p>Measure both directions. A convenient morning service may not solve getting home after a lab, society event or evening session. Check weekend options if returning home regularly is part of your plan.</p>'''),
('Turn minutes into a weekly comparison','''<p>Here is an invented example: 70 minutes each way, on four campus days, is 560 minutes—nine hours and twenty minutes of weekly travel. A 25-minute journey each way on the same schedule is 200 minutes, or three hours and twenty minutes.</p><p>The six-hour difference is not automatically a reason to move. It is a way to make the trade-off visible. Consider how reliably you can use travel time, what you carry and whether you would still have space for study and other commitments.</p>'''),
('Build a cost sheet from current quotes','''<div class="table-wrap"><table><thead><tr><th>Commuting</th><th>Moving closer</th></tr></thead><tbody><tr><td>Transport fares or vehicle costs</td><td>Accommodation and any deposit</td></tr><tr><td>Food bought on campus</td><td>Food and household essentials</td></tr><tr><td>Occasional alternative travel</td><td>Utilities if not included</td></tr><tr><td>Course equipment</td><td>Local transport and trips home</td></tr></tbody></table></div><p>Keep one-off costs separate from weekly or monthly costs. Check the length of any accommodation arrangement and what the quoted price includes. Do not compare a weekly travel estimate with a monthly rent figure without converting them to the same period.</p>'''),
('Check the parts of the timetable that can change','''<p>Ask the college whether the programme uses more than one campus, has early practical sessions or includes placements away from the main site. Request an illustrative timetable, while recognising that it may change.</p><p>For each option, write a fallback: missed connection, timetable change, an unavailable room or a placement in another location. You do not need a perfect answer to every scenario, but an option with no workable fallback deserves more research.</p>'''),
('Make the decision about fit, not the college image','''<p>Discuss the realistic costs and travel with whoever will support the decision. Compare the course itself too: moving closer to a programme you do not want does not fix the course mismatch.</p><p>Finish with a small decision sheet: strongest benefit, biggest constraint, unresolved question and next action for each option. If the figures are still estimates, label them. Before making commitments, verify current prices, availability and terms with the relevant providers.</p><p>Use location filters to widen your course search. You may find another programme worth investigating that changes the travel equation completely.</p>''')],
('Is commuting always cheaper?','Not necessarily. Compare your actual travel costs and schedule with accommodation, utilities and trips home. The answer depends on your circumstances and current quotes.'),[8,0,7])

CATS=['CAO & points','Study & school','Choosing a course','College life & routes']
LABELS=['Find your direction','Your best six','Choose what you love','Make a little progress','Practice with purpose','Find your level','Check the details','More than one route','Ask better questions','Picture your week']
ICONS=['↗','625','01','Aa','✓','∑','≡','6·7·8','?','⌂']
e=html.escape
logo='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m2 9 10-5 10 5-10 5-10-5Z"/><path d="M6 11v6c4 3 8 3 12 0v-6M22 9v7"/></svg>'
nav=f'<header class="site-header"><a class="brand" href="index.html">{logo}<span>CAO<span class="brand-light">finder</span></span></a><nav aria-label="Main navigation"><a href="index.html">Find courses</a><a href="index.html#/calculator">Points calculator</a><a href="blog.html" aria-current="page">Student blog</a></nav><a class="nav-cta" href="index.html">Find your course <span aria-hidden="true">↗</span></a></header>'
foot='<footer><a class="footer-brand" href="index.html">CAO Finder</a><p>A little clarity for your next big step.</p><div><a href="blog.html">Student blog</a><a href="index.html">Explore courses ↗</a></div><small>Independent student resource. Not affiliated with the Central Applications Office. Always confirm current requirements with CAO and the college.</small></footer>'
def head(title,desc,path,schema,script=False):
 return f'''<!doctype html><html lang="en-IE"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | CAO Finder</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{BASE+path}"><meta name="theme-color" content="#5954de"><meta property="og:type" content="{'website' if script else 'article'}"><meta property="og:site_name" content="CAO Finder"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{BASE+path}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="blog.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False).replace('<','\\u003c')}</script>{'<script src="blog.js" defer></script>' if script else ''}</head><body><a class="skip" href="#main">Skip to content</a>{nav}'''
def mins(a):
 return max(3,math.ceil(len(re.sub('<[^>]+>',' ',a['dek']+' '+a['take']+' '.join(h+' '+b for h,b in a['sections'])).split())/200))
def art(i):
 a=A[i]; c=CATS.index(a['cat'])
 return f'<div class="art art-{c}" aria-hidden="true"><span class="art-note">THE STUDENT EDIT</span><span class="art-symbol">{ICONS[i]}</span><span class="art-label">{LABELS[i]}</span><i></i></div>'
def card(i,compact=False):
 a=A[i]
 return f'''<article class="post-card {'compact' if compact else ''}" data-category="{e(a['cat'])}" data-search="{e((a['title']+' '+a['desc']+' '+a['cat']).lower())}"><a class="art-link" href="{a['slug']}.html" tabindex="-1" aria-hidden="true">{art(i)}</a><div class="post-info"><div class="meta"><span class="tag tag-{CATS.index(a['cat'])}">{e(a['cat'])}</span><span>{mins(a)} min read</span></div><h2><a href="{a['slug']}.html">{e(a['title'])}</a></h2><p>{e(a['desc'])}</p><a class="read-link" href="{a['slug']}.html" aria-label="Read: {e(a['title'])}">Read the guide <span aria-hidden="true">↗</span></a></div></article>'''
def cta():
 return '<section class="cta"><span class="eyebrow">YOUR NEXT STEP</span><h2>Find a course that feels like you.</h2><p>Take what you’ve learned and explore Irish college courses by points, subject, college and location.</p><a class="button" href="index.html">Explore courses <span aria-hidden="true">↗</span></a><span class="cta-doodle" aria-hidden="true">✳</span></section>'
indexschema={'@context':'https://schema.org','@type':'Blog','name':'The Student Edit — CAO Finder','url':BASE+'blog.html','description':'Practical guides for the Leaving Cert, CAO choices and college life.','blogPost':[{'@type':'BlogPosting','headline':a['title'],'url':BASE+a['slug']+'.html'} for a in A]}
out=head('Leaving Cert & CAO Student Blog','Straightforward guides to Leaving Cert study, CAO points, choosing college courses and student life. Find practical advice and your next step.','blog.html',indexschema,True)
out+='''<main id="main" class="blog-main"><section class="blog-hero"><div class="hero-copy"><span class="eyebrow"><span class="tiny-star">✳</span> THE STUDENT EDIT</span><h1>Big choices.<br>A little <span>clarity.</span></h1><p>Your guide to the Leaving Cert, CAO choices and what comes next. Practical advice, without the overwhelm.</p><div class="hero-caption"><span class="avatar-dot">✦</span> Made for your next chapter.</div></div><div class="hero-art" aria-hidden="true"><div class="paper paper-back"></div><div class="paper"><span class="paper-small">NOTE TO SELF</span><strong>You don’t need<br>it all figured<br>out. <span>Yet.</span></strong><div class="paper-line"></div><span class="paper-bottom">One step at a time. ↗</span></div><span class="hero-spark">✳</span><span class="hero-badge">YOU’VE GOT THIS</span></div></section><section class="guides" aria-labelledby="guides-title"><div class="section-top"><div><span class="eyebrow">A GOOD PLACE TO START</span><h2 id="guides-title">Guides for the way ahead</h2></div><label class="search"><span aria-hidden="true">⌕</span><input id="blog-search" type="search" placeholder="Search the guides…" aria-label="Search blog guides"></label></div><div class="filters" aria-label="Filter guides by topic">'''
for cat in ['All guides']+CATS:
 count=10 if cat=='All guides' else sum(a['cat']==cat for a in A)
 out+=f'<button type="button" data-filter="{e(cat)}" aria-pressed="{str(cat=="All guides").lower()}">{e(cat)} <span>{count}</span></button>'
out+='</div><p class="result-count" id="result-count" role="status" aria-live="polite">10 guides to help you take the next step</p><div id="posts">'+''.join(card(i) for i in range(10))+'</div><div id="empty" hidden><h3>No guides found</h3><p>Try another word or reset the filters.</p><button class="button" id="reset" type="button">Show all guides</button></div></section>'+cta()+'</main>'+foot+'</body></html>'
(ROOT/'blog.html').write_text(out)
for i,a in enumerate(A):
 path=a['slug']+'.html'
 schema={'@context':'https://schema.org','@graph':[{'@type':'BlogPosting','headline':a['title'],'description':a['desc'],'datePublished':DATE,'dateModified':DATE,'author':{'@type':'Organization','name':'CAO Finder','url':BASE},'publisher':{'@type':'Organization','name':'CAO Finder','url':BASE},'mainEntityOfPage':BASE+path,'articleSection':a['cat'],'inLanguage':'en-IE'},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'CAO Finder','item':BASE},{'@type':'ListItem','position':2,'name':'Student blog','item':BASE+'blog.html'},{'@type':'ListItem','position':3,'name':a['title'],'item':BASE+path}]}]}
 out=head(a['title'],a['desc'],path,schema)+f'<main id="main" class="article-main"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><a href="blog.html">Student blog</a></nav><header class="article-header"><span class="tag tag-{CATS.index(a["cat"])}">{e(a["cat"])}</span><h1>{e(a["title"])}</h1><p class="dek">{e(a["dek"])}</p><div class="byline"><span class="author-icon">CF</span><span>By CAO Finder <span class="byline-details"><time datetime="{DATE}">19 September 2026</time> · {mins(a)} min read</span></span></div></header><div class="article-layout"><aside class="toc" aria-label="On this page"><span class="eyebrow">IN THIS GUIDE</span><ol>'
 out+=''.join(f'<li><a href="#section-{j+1}">{e(h)}</a></li>' for j,(h,b) in enumerate(a['sections']))+'</ol><a href="blog.html">← All guides</a></aside><article class="article-body"><div class="takeaway"><span class="eyebrow">THE TAKEAWAY</span><p>'+e(a['take'])+'</p></div>'
 out+=''.join(f'<section id="section-{j+1}"><h2>{e(h)}</h2>{b}</section>' for j,(h,b) in enumerate(a['sections']))
 out+=f'<section class="faq"><span class="eyebrow">ONE MORE THING</span><h2>{e(a["faq"][0])}</h2><p>{e(a["faq"][1])}</p></section><p class="editor-note">Written by CAO Finder. Official rules are linked where relevant; examples and worksheets are illustrative. Check current CAO and college information for your application year.</p></article></div><section class="related"><span class="eyebrow">KEEP EXPLORING</span><h2>A little more help</h2><div class="related-grid">'+''.join(card(n,True) for n in a['related'])+'</div></section>'+cta()+'</main>'+foot+'</body></html>'
 (ROOT/path).write_text(out)
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE+p}</loc><lastmod>{DATE}</lastmod></url>' for p in ['','blog.html']+[a['slug']+'.html' for a in A])+'</urlset>')
print('Generated blog index, 10 articles and sitemap.')
