import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {unlink} from 'node:fs/promises';
import assert from 'node:assert/strict';
const output=new URL('../.search-test-build.mjs',import.meta.url);
await build({stdin:{contents:"export * from './src/lib/course-data'; export * from './src/lib/course-search';",resolveDir:process.cwd()},outfile:output.pathname,bundle:true,platform:'node',format:'esm',logLevel:'silent'});
try{
 const {courses,defaults,matches,parseCourseSearch,comparablePoints}=await import(pathToFileURL(output.pathname));
 const run=(query,changes={})=>courses.filter(c=>matches(c,{...defaults,query,...changes}));
 const nonempty=(query,test)=>{const list=run(query);assert(list.length>0,`No results: ${query}`);assert(list.every(test),`Wrong results: ${query}`);return list;};
 const example=nonempty('Dublin business low points',c=>c.location==='Dublin'&&c.categories.includes('Business'));
 assert.equal(parseCourseSearch('Dublin business low points').order,'low');
 assert.equal(parseCourseSearch('business lower points').order,'low');
 assert.equal(parseCourseSearch('business highest points').order,'high');
 assert.deepEqual(run('business Dublin').map(c=>c.code),run('Dublin business').map(c=>c.code));
 assert.deepEqual(run('show me business courses in Dublin please').map(c=>c.code),run('Dublin business').map(c=>c.code));
 nonempty('Dublin business under 400 points',c=>c.points<400&&c.points!==null&&!c.special&&c.location==='Dublin');
 nonempty('business up to 400 points',c=>c.points<=400&&c.points!==null&&!c.special);
 nonempty('engineering between 300 and 500 points',c=>c.points>=300&&c.points<=500&&!c.special);
 nonempty('Engineering 300–500 points',c=>c.points>=300&&c.points<=500&&!c.special);
 nonempty('Cork nursing under 450 points',c=>c.location==='Cork'&&c.title.toLowerCase().includes('nursing')&&c.points<450);
 nonempty('UCD economics',c=>c.college==='DN'&&c.categories.includes('Economics'));
 nonempty('Trinity business and law',c=>c.college==='TR'&&c.categories.includes('Law')&&c.categories.includes('Business'));
 nonempty('Dublin Business School',c=>c.college==='DB');
 nonempty('computer science Dublin',c=>c.location==='Dublin'&&c.categories.includes('Computing'));
 nonempty('IT in Cork',c=>c.location==='Cork'&&c.categories.includes('Computing'));
 nonempty('NUIG law',c=>c.college==='GY'&&c.categories.includes('Law'));
 nonempty('University College Cork nursing',c=>c.college==='CK'&&c.title.toLowerCase().includes('nursing'));
 nonempty('business >= 400',c=>c.points>=400&&!c.special);
 nonempty('business 400+',c=>c.points>=400&&!c.special);
 nonempty('business 400 points or less',c=>c.points!==null&&c.points<=400&&!c.special);
 nonempty('business 400 points or more',c=>c.points>=400&&!c.special);
 nonempty('business 400 points',c=>c.points!==null&&c.points<=400&&!c.special);
 assert.equal(parseCourseSearch('under 400').max,399);
 assert.equal(parseCourseSearch('above 400').min,401);
 assert.deepEqual(run('TR 580').map(c=>c.code),['TR580']);
 assert.deepEqual(run('tr580').map(c=>c.code),['TR580']);
 assert.deepEqual(run('Dublin buissness').map(c=>c.code),run('Dublin business').map(c=>c.code));
 assert.deepEqual(run('Dulbin business').map(c=>c.code),run('Dublin business').map(c=>c.code));
 assert(parseCourseSearch('Dulbin buissness').corrections.length===2);
 nonempty('accountant Dublin',c=>c.location==='Dublin'&&/account/i.test(c.title));
 nonempty('nurse Cork',c=>c.location==='Cork'&&/nurs/i.test(c.title));
 assert.equal(run('xyzzyplugh').length,0);
 assert.equal(run('Dublin business',{locations:['Cork']}).length,0);
 assert(run('business',{points:[300,350]}).every(c=>c.points>=300&&c.points<=350&&!c.special));
 assert(run('business',{colleges:['DN']}).every(c=>c.college==='DN'));
 assert(run('business',{levels:['7']}).every(c=>c.level===7));
 assert(run('business',{categories:['Finance']}).every(c=>c.categories.includes('Finance')&&c.categories.includes('Business')));
 assert(run('engineering',{subjects:['Mathematics']}).every(c=>c.requirements?.subjects.includes('Mathematics')));
 assert.equal(run('business above 600 under 300').length,0);
 assert.equal(run('').length,courses.filter(c=>c.level===8).length);
 assert.equal(run('   ').length,run('').length);
 assert.equal(comparablePoints({...courses[0],points:300,special:true}),null);
 assert.equal(comparablePoints({...courses[0],points:null,special:false}),null);
 const start=performance.now();for(let i=0;i<30;i++)run('Dublin business low points');
 console.log(`Search checks passed. Example: ${example.length} Dublin business matches; 30 searches in ${Math.round(performance.now()-start)}ms.`);
}catch(error){process.exitCode=1;console.error(error);}finally{await unlink(output);}
